#!/usr/bin/env bash

####################################################################
# BlackIP - Reputação CLI (Linux)                                  #
#                                                                  #
#                                                                  #
# Cybersec007  (c) 2020 ----------->>>>>>>>>>>>>>>>>               #
#                                                                  #
####################################################################

#### main ####
main() {

	[ $# -ne 1 ] && error "Rapaz, digite o dominio ou o IP pelo amor de Deus(rs)."

  fqdn=$(echo $1 | grep -P "(?=^.{5,254}$)(^(?:(?!\d+\.)[a-za-z0-9_\-]{1,63}\.?)+(?:[a-za-z]{2,})$)")

  if [[ $fqdn ]] ; then

    echo "Resenha|Cyber Analisando o Dominio: $1"

    domain=$(host $1 | head -n1 | awk '{print $4}')

    reverseit $domain "IP desconhecido ou invalido, dominio com problemas de DNS."
  else

    echo "Resenha|Cyber Analisando o IP: $1"
    reverseit $1 "IP desconhecido ou invalido."
  fi

  looplistanegra $1
}

#### reverseit ####
reverseit() {

  reverse=$(echo $1 |
  sed -ne "s~^\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)$~\4.\3.\2.\1~p")

  if [ "x${reverse}" = "x" ] ; then

    error $2 
    exit 1
  fi
}

#### looplistanegra ####
looplistanegra() {

  reverse_dns=$(dig +short -x $1)

   echo $1 Nome: ${reverse_dns:----}

  for bl in ${blacklists} ; do

####  printf $(env tz=utc date "+%y-%m-%d_%h:%m:%s_%z")
      printf "%-40s" " ${reverse}.${bl}."

      listed="$(dig +short -t a ${reverse}.${bl}.)"

      if [[ $listed ]]; then

        if [[ $listed == *"timed out"* ]]; then

          echo "[Tempo Expirado]" | cecho YELLOW 
        else
        
          echo "[Lista Negra] (${listed})" | cecho LRED
        fi
      else

          echo "[OK]" | cecho LGREEN
      fi
  done
}

#### error ####
error() {

  echo $0 error: $1 >&2
  exit 2
}

#### cecho ####
cecho(){
  LGREEN="\033[1;32m"
  LRED="\033[1;31m"
  YELLOW="\033[1;33m"
  NORMAL="\033[m"
 
  color=\$${1:-NORMAL}
 
  echo -ne "$(eval echo ${color})"
  cat
 
  echo -ne "${NORMAL}"
}

#### Blacklists####
blacklists="
z.mailspike.net 
rbl.interserver.net 
invaluement SIP 
hostkarma.junkemailfilter.com 
exploit.mail.abusix.zone 
cbl.abuseat.org 
black.junkemailfilter.com 
all.s5h.net 
0spam.fusionzero.com 
aspews.ext.sorbs.net 
backscatter.spameatingmonkey.net 
bl.blocklist.de 
bl.konstant.no 
bl.nosolicitado.org 
bl.scientificspam.net 
bl.spamcop.net 
bl.suomispam.net 
block.dnsbl.sorbs.net 
dnsbl-1.uceprotect.net 
dnsbl-3.uceprotect.net 
dnsbl.dronebl.org 
dnsbl.kempt.net 
dnsbl.sorbs.net 
dnsbl.tornevall.org 
dnsrbl.swinog.ch 
dyna.spamrats.com 
NordSpam 
ix.dnsbl.manitu.net 	
mail-abuse.blacklist.jippg.org 
multi.surbl.org 
new.spam.dnsbl.sorbs.net 
old.spam.dnsbl.sorbs.net 
problems.dnsbl.sorbs.net 
psbl.surriel.com 
rbl.blockedservers.com 
rbl2.triumf.ca 
relays.dnsbl.sorbs.net 	
safe.dnsbl.sorbs.net 
smtp.dnsbl.sorbs.net 	
spam.dnsbl.anonmails.de 
spam.pedantic.org 
spam.spamrats.com 
spamrbl.imp.ch 	
st.technovision.dk 
talosintelligence.com 
truncate.gbudb.net 	
web.dnsbl.sorbs.net 	
zombie.dnsbl.sorbs.net 
zen.spamhaus.org 
xbl.spamhaus.org 
torexit.dan.me.uk 
dnsbl.justspam.org 
black.mail.abusix.zone 
bl.mailspike.net 
access.redhawk.org 
all.spamrats.com 
b.barracudacentral.org 
bb.barracudacentral.org 
bl.drmx.org 
bl.rbl.scrolloutf1.com 
bl.score.senderscore.com 
bl.spameatingmonkey.net 
bl.worst.nosolicitado.org 
cart00ney.surriel.com 
db.wpbl.info 	
dnsbl-2.uceprotect.net 
dnsbl.cobion.com 
dnsbl.net.ua 
dnsbl.spfbl.net 
dnsbl.zapbl.net 	
dul.dnsbl.sorbs.net 
escalations.dnsbl.sorbs.net 
fnrbl.fast.net 	
http.dnsbl.sorbs.net 
invaluement SIP/24 	
ips.backscatterer.org 
l4.bbfh.ext.sorbs.net
misc.dnsbl.sorbs.net 	
netscan.rbl.blockedservers.com 
noptr.spamrats.com 
pbl.spamhaus.org 
proxies.dnsbl.sorbs.net 
rbl.abuse.ro 	
rbl.dns-servicios.com 	
rbl.realtimeblacklist.com 
recent.spam.dnsbl.sorbs.net 	
rep.mailspike.net 
sbl.spamhaus.org 
socks.dnsbl.sorbs.net 
spam.dnsbl.sorbs.net 
spam.rbl.blockedservers.com 	
spamlist.or.kr 
spamsources.fabel.dk 
mail-abuse.com 
ubl.unsubscore.com "

### initiate script ###
main $1 
